applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from .views import (

    All_Empleados,
    All_Empleados_by_Department,
    All_empleados_by_Jobs,
    Emplados_por_habilidades,
    Empleados_Detalles,
    Empleados_CreateView,
    successTemplateView,
    Empleado_UpdateView,
    Empleados_Delete,
    Listar_Empleados_Admin,
)

app_name = 'Empleados_app'

urlpatterns = [
    path('List_employees/', All_Empleados.as_view(), name="all_empleados"),
    path('by_area/<name>/', All_Empleados_by_Department.as_view(), name="empleados_by_area"),
    path('by_jobs/', All_empleados_by_Jobs.as_view(), name="empleados_by_jobs"),
    path('by_habilidades/', Emplados_por_habilidades.as_view(), name="emplados_by_habilidades"),
    path('empleados_details/<pk>/', Empleados_Detalles.as_view(), name="empleados_details"),
    path('empleados_create/', Empleados_CreateView.as_view(), name="empleados_create"),
    path('success/', successTemplateView.as_view(), name='success'),
    path('empleado_update/<pk>/', Empleado_UpdateView.as_view(), name='empleado_update'),
    path('empleado_delete/<pk>/', Empleados_Delete.as_view(), name='empleado_delete'),
    path('empleados_admin/', Listar_Empleados_Admin.as_view(), name='empleados_admin'),


]

empleado/urls.py
import document as document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from applications.persona.views import InicioView
from applications.persona.API.router import routers
from applications.departamento.API.router import routers as routers_departamento
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Employee API",
        default_version='v1',
        description="Employee API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('departamento/', include('applications.departamento.urls')),
    path('api/', include(routers.urls)),
    path('api/', include(routers_departamento.urls)),
    path('api/', include('applications.user.API.router')),
    path('empleado/', include('applications.persona.urls')),
    path('home/', include('applications.home.urls')),
    path('', InicioView.as_view(), name='inicio'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Habilidades(models.Model):
    Habilidades = models.CharField('Habilidades', max_length=50)

    class Meta:
        verbose_name ='Habilidades'
        verbose_name_plural = "Habilidades"

    def __str__(self):
        return f"{self.Habilidades}"


class Persona(models.Model):

    JOBS_CHOICES = (
        ("0", "COUNTER"),
        ("1", "ADMINISTRATOR"),
        ("2", "Economist"),
        ("3", "Others"),
    )

    FirstName = models.CharField("Name", max_length=50)
    LastName = models.CharField("Last Name", max_length=50)
    Jobs = models.CharField("Jobs", choices=JOBS_CHOICES, max_length=1)
    full_name = models.CharField("Full Name", max_length=100, blank=True)
    departament = models.ForeignKey(Departamento, related_name='Departamento', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="empleado", blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    resume = RichTextField(null=False)

    class Meta:
        verbose_name='Persona'
        verbose_name_plural = 'Persona'
        ordering = ('-FirstName',)
        unique_together = ('FirstName', 'LastName')

    def __str__(self):
        return f"{self.FirstName} {self.LastName} {self.departament}"

templates/usuario/all_empleados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee</title>
</head>
<body>

<h1>Lista de Empleados</h1>

<ul>
    {% for employ in Empleados_list %}

    <li>{{employ}}</li>

    {% endfor %}
</ul>

<nav>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                <li {% if page_obj.number == i %} class="active" {% endif %}>
                    <a href="?page={{i}}">{{ i }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% endif %}
        </ul>
    {% endif %}
</nav>


</body>
</html>

templates/usuario/create_empleados.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}


{% block body %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Registrar Empleado</h1>
        <form method="post" class="cell grid-x grid-margin-x" enctype="multipart/form-data">{% csrf_token %}
         <div class="cell large-6">
            <label>Nombre
                {{form.FirstName}}
            </label>
        </div>


    <div class="cell large-6">
        <label>Apellidos
            {{form.LastName}}
        </label>
    </div>


    <div class="cell large-6">
        <label>Trabajo
            {{form.Jobs}}
        </label>
    </div>


    <div class="cell large-6">
        <label>Departamento
            {{form.departament}}
        </label>
    </div>

            <div class="cell large-12">
                <label>Habilidades
                    {{form.habilidades}}
                </label>
            </div>

            <div class="cell large-12">
                <label>Imagen de Perfil
                    {{form.avatar}}

                </label>
            </div>


            <div class="cell large-12">
                <button class="submit success button">Guardar</button>
            </div>

        </form>

</div>

</div>





{% endblock body %}

templates/usuario/eliminar_empleados.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}


{% block body %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{empleado.FirstName}} </h1>

        <form class="cell" method="post">{% csrf_token %}
            <div class="callout alert">
                <h5>Eliminar</h5>
                <p>Esta seguro que desea eliminar este empleado?</p>
                <button class="submit alert button">Confirmar</button>
            </div>
        </form>


    </div>

</div>


{% endblock body %}

templates/usuario/empleado_update.html
{% extends 'base.html' %}

{% block title %} Actualizar Empleados{% endblock title %}


{% block body %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleados
        </h1>
        
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombre
                            {{form.FirstName}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos
                        {{form.LastName}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Trabajo
                        {{form.Jobs}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Departamento
                        {{form.departament}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Avatar
                        {{form.avatar}}
                    </label>
                </div>


                <div class="cell large-6">
                    <label>Apellidos
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Actualizar</button>
                </div>

            </form>
            
        </div>
        
    </div>
    
</div>

{% endblock body %}

templates/usuario/empleados_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Lista de Departamentos {% endblock title %}



{% block body %}
{% include 'includes/header.html' %}



        <div class="grid-container">
            <div class="grid-x grid-margin-x align-center">
                <h1 class="cell" style="text-align:center;">Detalle Empleados</h1>
                        <div class="card large-4" style="width: 300px;">
          <div class="card-divider">
            <h4 style="text-align:center;" class="align-center ">{{empleados.FirstName}} {{empleados.LastName}}</h4>
          </div>
           {% if empleados.avatar %}
          <img src="{{empleados.avatar.url}}">
            {% else %}
          <img src="{% static 'img/avatar.png' %}">
            {% endif %}
          <div class="card-section">
              <p>Trabajo: {{empleados.get_Jobs_display}}</p>
              <p>Departamento: {{empleados.departament.short_name}}</p>
              <p><span class="label">Habiliadades:</span></p>
              <ul class="vertical menu">
                  {%  for h in empleados.habilidades.all  %}
                  <li>{{h.Habilidades}}</li>
                  {%  endfor  %}
              </ul>
          </div>
        </div>

            </div>
</div>

{% endblock body %}

templates/usuario/empleados_por_habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>By Habilidades</title>
</head>
<body>
<h2>Lista de Habbilidades por empleados </h2>
<form method="get" > {% csrf_token %}
    <input type="text" id="kword" name="kword"  placeholder="Ingrese un id">
    <button type="submit">Buscar</button>

</form>



<ul>
    {% for empleado in empleados %}
    <b>{{empleado.FirstName}}</b>
    <li>{{empleado}}</li>
    {% endfor %}
</ul>

</body>
</html>

templates/usuario/employees_by_department.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}



{% block body %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados por departamento</h1>
            <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Buscar">
                </div>
                <div class="cell large-2">
                    <button class="submit success button">Buscar</button>
                </div>

            </form>
        <div class="cell">


            <table>
  <thead>
    <tr>
      <th width="200">ID</th>
      <th>FIRST NAME</th>
      <th width="150">LAST NAME</th>
      <th width="150">DEPARTMENT</th>
       <th width="150">ACTION</th>
    </tr>
  </thead>
  <tbody>
   {% for employ in empleados %}
    <tr>
      <td>{{employ.id}}</td>
      <td>{{employ.FirstName}}</td>
      <td>{{employ.LastName}}</td>
      <td>{{employ.departament}}</td>
        <td><a class="button warning" href="{% url 'Empleados_app:empleados_details' employ.id %}">Show</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
        </div>
        </h1>
    </div>
    <ul>
</ul>
</div>
{% if is_paginated %}
<nav aria-label="Pagination">
  <ul class="pagination text-center">

      {% if page_obj.has_previous %}
    <li class="pagination-next"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

       {% for i in paginator.page_range %}
      <li {% if page_obj.number == i %} class="current" {% endif %}>
          <a href="?page={{i}}">{{ i }}</a>
      </li>
      {% endfor %}


    <li class="ellipsis"></li>
      {% if page_obj.has_next %}
    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}

  </ul>
</nav>
{% endif %}
{% endblock body %}

templates/usuario/employees_by_jobs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>By Jobs</title>
</head>
<body>

<h1>Empleados por Jobs</h1>

<form method="get" > {% csrf_token %}


    <label>Selecciona un trabajo:</label>
  <select name="kword" id="kword">
    <option value="1">ADMINTRADOR</option>
    <option value="0">COUNTER</option>
    <option value="2">Economist</option>
    <option value="3">Others</option>
  </select>



    <button type="submit">Buscar</button>

</form>

<h2>Lista de empleados por area</h2>

<ul>
    {% for empleado in empleados %}
    <li>{{empleado}}</li>
    {% endfor %}
</ul>



</body>
</html>

templates/usuario/listar_empeados.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}



{% block body %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
            <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Buscar">
                </div>
                <div class="cell large-2">
                    <button class="submit success button">Buscar</button>
                </div>

            </form>
        <div class="cell">


            <table>
  <thead>
    <tr>
      <th width="200">ID</th>
      <th>FIRST NAME</th>
      <th width="150">LAST NAME</th>
      <th width="150">DEPARTMENT</th>
       <th width="150">ACTION</th>
    </tr>
  </thead>
  <tbody>
   {% for employ in empleados %}
    <tr>
      <td>{{employ.id}}</td>
      <td>{{employ.FirstName}}</td>
      <td>{{employ.LastName}}</td>
      <td>{{employ.departament}}</td>
      <td><a class="button success" href="{% url 'Empleados_app:empleado_update' employ.id %}">Editar</a></td>
        <td><a class="button alert" href="{% url 'Empleados_app:empleado_delete' employ.id %}">Eliminar</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
        </div>
        </h1>
    </div>
    <ul>
</ul>
</div>
{% if is_paginated %}
<nav aria-label="Pagination">
  <ul class="pagination text-center">

      {% if page_obj.has_previous %}
    <li class="pagination-next"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

       {% for i in paginator.page_range %}
      <li {% if page_obj.number == i %} class="current" {% endif %}>
          <a href="?page={{i}}">{{ i }}</a>
      </li>
      {% endfor %}


    <li class="ellipsis"></li>
      {% if page_obj.has_next %}
    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}

  </ul>
</nav>
{% endif %}
{% endblock body %}

templates/usuario/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Empleado  correctamente</h1>
</body>
</html>