applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from .views import DepartamentoView, List_DepartamentoView

app_name = 'Departamento_app'

urlpatterns = [
    path('add_departamento/', DepartamentoView.as_view(), name='add_departamento'),
    path('list_departamentos/', List_DepartamentoView.as_view(), name='list_departamentos'),

]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from .views import (

    All_Empleados,
    All_Empleados_by_Department,
    All_empleados_by_Jobs,
    Emplados_por_habilidades,
    Empleados_Detalles,
    Empleados_CreateView,
    successTemplateView,
    Empleado_UpdateView,
    Empleados_Delete,
    Listar_Empleados_Admin,
)

app_name = 'Empleados_app'

urlpatterns = [
    path('List_employees/', All_Empleados.as_view(), name="all_empleados"),
    path('by_area/<name>/', All_Empleados_by_Department.as_view(), name="empleados_by_area"),
    path('by_jobs/', All_empleados_by_Jobs.as_view(), name="empleados_by_jobs"),
    path('by_habilidades/', Emplados_por_habilidades.as_view(), name="emplados_by_habilidades"),
    path('empleados_details/<pk>/', Empleados_Detalles.as_view(), name="empleados_details"),
    path('empleados_create/', Empleados_CreateView.as_view(), name="empleados_create"),
    path('success/', successTemplateView.as_view(), name='success'),
    path('empleado_update/<pk>/', Empleado_UpdateView.as_view(), name='empleado_update'),
    path('empleado_delete/<pk>/', Empleados_Delete.as_view(), name='empleado_delete'),
    path('empleados_admin/', Listar_Empleados_Admin.as_view(), name='empleados_admin'),


]

empleado/urls.py
import document as document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from applications.persona.views import InicioView
from applications.persona.API.router import routers
from applications.departamento.API.router import routers as routers_departamento
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Employee API",
        default_version='v1',
        description="Employee API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('departamento/', include('applications.departamento.urls')),
    path('api/', include(routers.urls)),
    path('api/', include(routers_departamento.urls)),
    path('api/', include('applications.user.API.router')),
    path('empleado/', include('applications.persona.urls')),
    path('home/', include('applications.home.urls')),
    path('', InicioView.as_view(), name='inicio'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <a href="/" class="menu-text">Empleados</a>
      <li class="has-submenu"><a href="{% url 'Empleados_app:all_empleados' %}">Listar Empleados</a></li>
      <li><a href="{% url 'Departamento_app:list_departamentos' %}">Departamentos</a></li>
      <li><a href="{% url 'Departamento_app:add_departamento' %}">Nuevo Departamento</a></li>
      <li><a href="{% url 'Empleados_app:empleados_admin' %}">Admninistrar</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><a class="button" href="{% url 'Empleados_app:empleados_create' %}">Registrar Empleados</a></li>
    </ul>
  </div>
</div>