applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from .views import DepartamentoView, List_DepartamentoView

app_name = 'Departamento_app'

urlpatterns = [
    path('add_departamento/', DepartamentoView.as_view(), name='add_departamento'),
    path('list_departamentos/', List_DepartamentoView.as_view(), name='list_departamentos'),

]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from .views import (

    All_Empleados,
    All_Empleados_by_Department,
    All_empleados_by_Jobs,
    Emplados_por_habilidades,
    Empleados_Detalles,
    Empleados_CreateView,
    successTemplateView,
    Empleado_UpdateView,
    Empleados_Delete,
    Listar_Empleados_Admin,
)

app_name = 'Empleados_app'

urlpatterns = [
    path('List_employees/', All_Empleados.as_view(), name="all_empleados"),
    path('by_area/<name>/', All_Empleados_by_Department.as_view(), name="empleados_by_area"),
    path('by_jobs/', All_empleados_by_Jobs.as_view(), name="empleados_by_jobs"),
    path('by_habilidades/', Emplados_por_habilidades.as_view(), name="emplados_by_habilidades"),
    path('empleados_details/<pk>/', Empleados_Detalles.as_view(), name="empleados_details"),
    path('empleados_create/', Empleados_CreateView.as_view(), name="empleados_create"),
    path('success/', successTemplateView.as_view(), name='success'),
    path('empleado_update/<pk>/', Empleado_UpdateView.as_view(), name='empleado_update'),
    path('empleado_delete/<pk>/', Empleados_Delete.as_view(), name='empleado_delete'),
    path('empleados_admin/', Listar_Empleados_Admin.as_view(), name='empleados_admin'),


]

empleado/urls.py
import document as document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from applications.persona.views import InicioView
from applications.persona.API.router import routers
from applications.departamento.API.router import routers as routers_departamento
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Employee API",
        default_version='v1',
        description="Employee API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('departamento/', include('applications.departamento.urls')),
    path('api/', include(routers.urls)),
    path('api/', include(routers_departamento.urls)),
    path('api/', include('applications.user.API.router')),
    path('empleado/', include('applications.persona.urls')),
    path('home/', include('applications.home.urls')),
    path('', InicioView.as_view(), name='inicio'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.


class Departamento(models.Model):
    name = models.CharField("Nombre", max_length=50)
    short_name = models.CharField("Nombre Corto", max_length=50)
    annulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name='Departamento'
        verbose_name_plural='Departamento'
        ordering = ['-name']
        unique_together = ('name', 'short_name')

    def __str__(self):
        return str(self.id) + " " + self.name + " " + self.short_name

applications/departamento/forms.py
from django import forms

class DepartamentoFormView(forms.Form):
    JOBS_CHOICES = (
        ("0", "COUNTER"),
        ("1", "ADMINISTRATOR"),
        ("2", "Economist"),
        ("3", "Others"),
    )

    Nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    departamento = forms.CharField(max_length=100)
    short_name = forms.CharField(max_length=100)
    cargos = forms.ChoiceField(choices=JOBS_CHOICES)

applications/departamento/API/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from .serializer import DepartamentoSerializer
from applications.departamento.models import Departamento


class DepartamentoViewSet(ModelViewSet):
    queryset = Departamento.objects.all()
    serializer_class = DepartamentoSerializer

applications/departamento/views.py
from django.views.generic.edit import FormView
from .forms import DepartamentoFormView
from applications.persona.models import Persona
from django.urls import reverse_lazy
from .models import Departamento
from django.views.generic import (
    ListView,
)

class DepartamentoView(FormView):
    template_name = 'departamento/add_departamento.html'
    form_class = DepartamentoFormView
    success_url = reverse_lazy("Departamento_app:list_departamentos")

    def form_valid(self,form):

        nombre = form.cleaned_data['Nombre']
        apellido = form.cleaned_data['apellido']
        cargos = form.cleaned_data['cargos']

        Persona.objects.create(
            FirstName=nombre,
            LastName=apellido,
            Jobs=cargos,
            full_name=nombre + " " + apellido,
            departament=Departamento.objects.create(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
    )
        return super(DepartamentoView, self).form_valid(form)




class List_DepartamentoView(ListView):
    template_name = "departamento/all_departamentos.html"
    paginate_by = 4
    model = Departamento
    context_object_name = 'departamentos'

    def get_queryset(self):
        palabraClave = self.request.GET.get('kword','')
        lista = Departamento.objects.filter(name__icontains=palabraClave)
        return lista

templates/departamento/add_departamento.html
{% extends 'base.html' %}

{% block title %} Lista de Empleados {% endblock title %}


{% block body %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Registrar Departamento</h1>
        <form method="post" class="callout cell grid-x grid-margin-x">{% csrf_token %}

            <div class="cell large-6">
                <label>Encargado de Departamento
                    {{form.Nombre}}
                </label>
            </div>


            <div class="cell large-6">
                <label>Apellidos
                    {{form.apellido}}
                </label>
            </div>


            <div class="cell large-6">
                <label>Nombre del departamento
                    {{form.departamento}}
                </label>
            </div>

            <div class="cell large-6">
                <label>Cargo del departamento
                    {{form.cargos}}
                </label>
            </div>


            <div class="cell large-6">
                <label>Short Name de Departamento
                    {{form.short_name}}
                </label>
            </div>

            <div class="cell large-12">
                <button class="submit success button">Guardar</button>
            </div>

        </form>

    </div>
</div>

{% endblock body %}

templates/departamento/all_departamentos.html
{% extends 'base.html' %}

{% block title %} Lista de Departamentos {% endblock title %}



{% block body %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Departamentos</h1>
            <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Buscar">
                </div>
                <div class="cell large-2">
                    <button class="submit success button">Buscar</button>
                </div>

            </form>
        <div class="cell">


            <table>
  <thead>
    <tr>
      <th width="200">ID</th>
      <th>NAME</th>
      <th width="150">SORT NAME</th>
       <th width="150">ACTION</th>
    </tr>
  </thead>
  <tbody>
   {% for dep in departamentos %}
    <tr>
      <td>{{dep.id}}</td>
      <td>{{dep.name}}</td>
      <td>{{dep.short_name}}</td>
      <td><a class="button warning" href="{% url 'Empleados_app:empleados_by_area' dep.name %}">Ver Empleados</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
        </div>
        </h1>
    </div>
    <ul>
</ul>
</div>
{% if is_paginated %}
<nav aria-label="Pagination">
  <ul class="pagination text-center">

      {% if page_obj.has_previous %}
    <li class="pagination-next"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

       {% for i in paginator.page_range %}
      <li {% if page_obj.number == i %} class="current" {% endif %}>
          <a href="?page={{i}}">{{ i }}</a>
      </li>
      {% endfor %}


    <li class="ellipsis"></li>
      {% if page_obj.has_next %}
    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}

  </ul>
</nav>
{% endif %}


{% endblock body %}